require 'bundler'
Bundler::GemHelper.install_tasks

require 'fileutils'
require 'rspec/core/rake_task'

RSpec::Core::RakeTask.new

task :default do
  if Dir["spec/dummy"].empty?
    Rake::Task[:test_app].invoke
    Dir.chdir("../../")
  end
  Rake::Task[:spec].invoke
end

desc "Generates a dummy app for testing"
task :test_app do
  ENV['LIB_NAME'] = 'solidus_multi_domain'
  ENV['RAILS_ENV'] = 'test'

  require 'solidus_multi_domain'

  unless defined?(Solidus::InstallGenerator)
    require 'generators/solidus/install/install_generator'
  end
  require 'generators/spree/dummy/dummy_generator'

  Spree::DummyGenerator.start ["--lib_name=solidus_multi_domain", "--quiet"]

  # The Solidus generators chdir into the dummy app, so post-DummyGenerator paths
  # are relative to the dummy root (== current working directory at this point).
  dummy_root = Dir.pwd

  # On Rails 8 the generated dummy app ships without app/assets/config/manifest.js,
  # so sprockets-rails 3.5 raises Sprockets::Railtie::ManifestNeededError the first
  # time the app boots. Solidus::InstallGenerator boots the app, so seed the manifest
  # BEFORE running it. (mirrors solidusio/solidus#3379, solidusio/solidus#6327)
  manifest_dir = File.join(dummy_root, 'app', 'assets', 'config')
  manifest_file = File.join(manifest_dir, 'manifest.js')
  unless File.exist?(manifest_file)
    FileUtils.mkdir_p(manifest_dir)
    File.write(manifest_file, "//= link_tree ../images\n//= link_directory ../stylesheets .css\n")
  end

  Solidus::InstallGenerator.start ["--lib_name=solidus_multi_domain", "--auto-accept", "--with-authentication=false", "--payment-method=none", "--migrate=false", "--seed=false", "--sample=false", "--quiet", "--user_class=Spree::LegacyUser"]

  # The Solidus::InstallGenerator copies every engine migration into the dummy's
  # db/migrate with fresh timestamps, so the dummy's own db/migrate is the complete,
  # authoritative migration set. But Rails ALSO keeps each engine's source db/migrate
  # on the host migrator (via migration_railties), so the originals appear as a second,
  # unrecorded copy and maintain_test_schema! raises PendingMigrationError. Restrict
  # the dummy's migration source to its own db/migrate so the version set is internally
  # consistent. (mirrors the single-source migrations_paths of
  # solidusio/solidus Spree::TestingSupport::DummyApp)
  File.write(
    File.join(dummy_root, 'config', 'initializers', 'dummy_migration_paths.rb'),
    <<~RUBY
      # Generated by rake test_app. The dummy's own db/migrate already contains every
      # engine migration (copied at install). Pin the migrator to it so engine source
      # paths don't show up as duplicate "pending" migrations against maintain_test_schema!.
      Rails.application.config.after_initialize do
        local = Rails.root.join('db', 'migrate').to_s
        Rails.application.config.paths['db/migrate'] = [local]
        ActiveRecord::Migrator.migrations_paths = [local]
      end
    RUBY
  )

  puts "Setting up dummy database..."
  # rake test_app's chained db:create/db:migrate can leave the sqlite file empty;
  # split into discrete bin/rails invocations.
  sh "bin/rails db:environment:set RAILS_ENV=test"
  sh "bin/rails db:drop db:create RAILS_ENV=test"
  sh "bin/rails db:migrate VERBOSE=false RAILS_ENV=test"
end
